name: Docker Build and Publish

on: push  # O workflow será acionado sempre que ocorrer um push no repositório

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/jogo-do-galo:latest .

